[package]
name = "keepr-vault"
version = "0.1.0"
description = "Time-locked USDC vaults on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "keepr_vault"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
default = []

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = "0.31.1"

[profile.release]
overflow-checks = true
